GET http://localhost:8080/users
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2Nlc3MiLCJqdGkiOiJjMmY4ZDZjZi1mOTBhLTQ1Y2UtODlhOC1hOTI3YTRlMGRhN2QiLCJleHAiOjE1NTEwMjAxNTIsIm5iZiI6MTU1MTAxMzc1MiwiaWF0IjoxNTUxMDEzNzUyLCJpZGVudGl0eSI6InRlc3QifQ.rWrWmEU31W5WykheT-omj6XwRAMBXnSlMgSNLJ_2yxtwWeFMGESwQAfRJdY0Xb1goVUtLAy59ijw4khBFm7g3A
Accept: application/json

###