GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2Nlc3MiLCJqdGkiOiI0Y2RkMDVhZC02MWVjLTQzM2MtOTBjNC04MzI5Yzc3OTYzMGYiLCJleHAiOjE1NTE1MDcxODMsIm5iZiI6MTU1MTUwMDc4MywiaWF0IjoxNTUxNTAwNzgzLCJpZGVudGl0eSI6InRlc3QifQ.ubxuO2GvLBPXXOd2HMebkNEL_efjwLkchEgxG1BQZbFT0kUzKROy2h04oViHJBBg_21VVM5JIh64AsHWmt3UTg
Accept: application/json

###