GET http://localhost:8080/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyZWZyZXNoIiwianRpIjoiMjhmOWY1NDAtNmVjMC00NTUyLTlkOTMtZTAwMGVlZTExYmIyIiwiZXhwIjoxNTU0MDMyMjUwLCJuYmYiOjE1NTE0NDAyNTAsImlhdCI6MTU1MTQ0MDI1MCwiaWRlbnRpdHkiOiJ0ZXN0In0.YK6VWHi58BbwvXcCi_gZcH3ITEufIte7xFVIQAz3BRAtVktnR9IQpbLLz1XAaGsmEoqrXxwzhA90m1X1f1olKQ
Accept: application/json

###