GET http://localhost:8080/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyZWZyZXNoIiwianRpIjoiYjZkNDJkYWMtYWEwMi00NjBmLWE5NDctYWM2Mjg5Yjg5MzE4IiwiZXhwIjoxNTUzNjExMjUxLCJuYmYiOjE1NTEwMTkyNTEsImlhdCI6MTU1MTAxOTI1MSwiaWRlbnRpdHkiOiJ0ZXN0In0.7P9ilNjGZstaN_TK46VhSCtDKO0PYvRdjgZby6TvVF-LpxN-xOticDN9zpghgou4c2M7sRi8PQJBOj4ktA4vGg
Accept: application/json

###