DELETE http://localhost:8080/posts/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2Nlc3MiLCJqdGkiOiIyMzFjNDY0MS05YjM3LTRiNmYtYjQwNC1kZDgxYTk1OGYxZWYiLCJleHAiOjE1NTEwOTQyMjksIm5iZiI6MTU1MTA4NzgyOSwiaWF0IjoxNTUxMDg3ODI5LCJpZGVudGl0eSI6InRlc3QifQ.uBo9lDT9ntlaX_A3_cNfJVzvrFXMdrFkg7bQsvXl3A18LEBnxVq-WHhFYN4NkNKU3EB2fRVAMaBHzlBnh2KwDA

###